/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.HeadlessException;
import java.sql.SQLException;

public class ChucVuForm extends javax.swing.JFrame {
    
    private dao.ChucVuDAO dao = new dao.ChucVuDAO(); 
    private javax.swing.table.DefaultTableModel tblModel;
    /**
     * Creates new form PhongBanForm
     */
    public ChucVuForm() {
        initComponents();
        getContentPane().setBackground(java.awt.Color.WHITE); 
        initTable();
        loadTable();
//      txtmacv.setEnabled(false);

        getContentPane().setBackground(java.awt.Color.WHITE);
        
        javax.swing.JPanel decorator = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawLine(450, 15, 450, getHeight() - 30);
            }
            @Override
            public boolean contains(int x, int y) { return false; }
        };
        decorator.setOpaque(false);
        setGlassPane(decorator);
        decorator.setVisible(true);
    }
    
    // 1. Hàm định dạng bảng
    private void initTable() {
        tblModel = (javax.swing.table.DefaultTableModel) tbchucvu.getModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã CV", "Tên CV", "Phụ cấp", "Ghi chú"});
        
        tbchucvu.setShowVerticalLines(true); 
        tbchucvu.setShowHorizontalLines(true);
        tbchucvu.setGridColor(new java.awt.Color(190, 190, 190));
        
        javax.swing.table.JTableHeader header = tbchucvu.getTableHeader();
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13)); 
        header.setBackground(java.awt.Color.WHITE); 
        header.setForeground(new java.awt.Color(70, 70, 70));
        header.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(200, 200, 200)));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)),
            "Danh sách chức vụ",
            javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
            javax.swing.border.TitledBorder.DEFAULT_POSITION,
            new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13),
            new java.awt.Color(41, 128, 185) 
        ));
        
        javax.swing.table.TableColumnModel columnModel = tbchucvu.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(50);  // Mã CV
        columnModel.getColumn(1).setPreferredWidth(130); // Tên CV
        columnModel.getColumn(2).setPreferredWidth(100); // Phụ Cấp
        columnModel.getColumn(3).setPreferredWidth(150); // Ghi chú
    }

    // 2. Hàm tải dữ liệu từ CSDL lên bảng
    private void loadTable() {
        tblModel.setRowCount(0); 
        java.util.List<model.ChucVu> list = dao.getAll();
        for (model.ChucVu cv : list) {
            tblModel.addRow(new Object[]{
                cv.getMaCV(),
                cv.getTenCV(),
                String.format("%.0f", cv.getPhuCap()), // Ép kiểu mất .0
                cv.getGhiChu() // Đã lấy được Ghi chú
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmacv = new javax.swing.JTextField();
        txttencv = new javax.swing.JTextField();
        txtphucapcv = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtghichucv = new javax.swing.JTextArea();
        btnthemcv = new javax.swing.JButton();
        btnxoacv = new javax.swing.JButton();
        btnsuacv = new javax.swing.JButton();
        btnlamlaicv = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbchucvu = new javax.swing.JTable();
        txtSearchcv = new javax.swing.JTextField();
        btnSearchcv = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cập nhật phòng ban");
        setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Thông tin chức vụ");

        jLabel2.setText("Mã chức vụ:");

        jLabel3.setText("Tên chức vụ:");

        jLabel4.setText("Phụ cấp:");

        jLabel5.setText("Ghi chú:");

        txtghichucv.setColumns(20);
        txtghichucv.setRows(5);
        jScrollPane1.setViewportView(txtghichucv);

        btnthemcv.setText("Thêm");
        btnthemcv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemcvActionPerformed(evt);
            }
        });

        btnxoacv.setText("Xóa");
        btnxoacv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoacvActionPerformed(evt);
            }
        });

        btnsuacv.setText("Sửa");
        btnsuacv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuacvActionPerformed(evt);
            }
        });

        btnlamlaicv.setText("Làm lại");
        btnlamlaicv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlamlaicvActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Danh sách chức vụ hiện có");

        tbchucvu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã CV", "Tên CV", "Phụ cấp", "Ghi chú"
            }
        ));
        tbchucvu.setName(""); // NOI18N
        tbchucvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbchucvuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbchucvu);

        btnSearchcv.setText("Tìm");
        btnSearchcv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchcvActionPerformed(evt);
            }
        });

        jLabel7.setText("Tìm kiếm:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnthemcv)
                        .addGap(18, 18, 18)
                        .addComponent(btnxoacv)
                        .addGap(18, 18, 18)
                        .addComponent(btnsuacv)
                        .addGap(18, 18, 18)
                        .addComponent(btnlamlaicv))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(txtmacv)
                            .addComponent(txttencv)
                            .addComponent(txtphucapcv)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchcv, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnSearchcv, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtmacv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSearchcv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchcv))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txttencv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtphucapcv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnthemcv)
                            .addComponent(btnxoacv)
                            .addComponent(btnsuacv)
                            .addComponent(btnlamlaicv)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemcvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemcvActionPerformed
        String tenCV = txttencv.getText().trim();
        String phuCapStr = txtphucapcv.getText().trim();
        String ghiChu = txtghichucv.getText().trim(); // Lấy Ghi chú từ form

        if (tenCV.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập tên chức vụ!");
            txttencv.requestFocus();
            return;
        }

        double phuCap = 0;
        try {
            if (!phuCapStr.isEmpty()) {
                phuCap = Double.parseDouble(phuCapStr);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Phụ cấp phải là số hợp lệ!");
            return;
        }

        try {
            java.sql.Connection conn = util.DBConnection.getConnection();
            
            // Gọi thủ tục 3 tham số
            String sql = "{CALL sp_ThemChucVu(?, ?, ?)}";
            java.sql.CallableStatement cs = conn.prepareCall(sql);
            cs.setString(1, tenCV);
            cs.setDouble(2, phuCap);
            cs.setString(3, ghiChu);
            
            cs.execute();
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm chức vụ thành công!");
            
            loadTable(); 
            btnlamlaicvActionPerformed(evt); 
            cs.close();
            conn.close();
        } catch (java.awt.HeadlessException | java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi Thêm: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnthemcvActionPerformed

    private void tbchucvuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbchucvuMouseClicked
        int row = tbchucvu.getSelectedRow();
        if (row >= 0) {
            txtmacv.setText(tbchucvu.getValueAt(row, 0).toString());
            txttencv.setText(tbchucvu.getValueAt(row, 1).toString());
            
            Object phuCap = tbchucvu.getValueAt(row, 2);
            txtphucapcv.setText(phuCap != null ? phuCap.toString() : "0");
            
            // Click bảng thì đổ Ghi chú lên Form
            Object ghiChu = tbchucvu.getValueAt(row, 3);
            txtghichucv.setText(ghiChu != null ? ghiChu.toString() : "");
        }
    }//GEN-LAST:event_tbchucvuMouseClicked

    private void btnxoacvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoacvActionPerformed
        // 1. Lấy chuỗi từ ô nhập Mã CV
        String maCVStr = txtmacv.getText().trim();

        // 2. Kiểm tra rỗng (Giống trong ảnh)
        if (maCVStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn hoặc nhập mã chức vụ cần xóa!");
            return;
        }

        int maCV;
        
        // 3. Kiểm tra định dạng số (Giống trong ảnh)
        try {
            maCV = Integer.parseInt(maCVStr);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Mã chức vụ phải là số!");
            return;
        }

        // 4. Hiển thị hộp thoại xác nhận (Giống trong ảnh)
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                "Bạn có chắc muốn xóa chức vụ này?", 
                "Xác nhận", 
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        // 5. Nếu chọn YES (Đồng ý xóa)
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                // Gọi hàm deleteChucVu từ DAO 
                if (dao.deleteChucVu(maCV)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Xóa chức vụ thành công!");
                    
                    // Xóa xong thì tải lại bảng cho dữ liệu mới nhất
                    loadTable(); 
                    
                    txtmacv.setText("");
                    txttencv.setText("");
                    txtghichucv.setText("");
                } else {
                    // Nếu DAO trả về false 
                    javax.swing.JOptionPane.showMessageDialog(this, "Xóa thất bại! Vui lòng kiểm tra lại dữ liệu.");
                }
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi hệ thống: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnxoacvActionPerformed

    private void btnsuacvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuacvActionPerformed
        String maCVStr = txtmacv.getText().trim();
        if (maCVStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng click chọn một chức vụ trên bảng để sửa!");
            return;
        }

        String tenCV = txttencv.getText().trim();
        String phuCapStr = txtphucapcv.getText().trim();
        String ghiChu = txtghichucv.getText().trim(); // Lấy Ghi chú mới

        if (tenCV.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tên chức vụ không được để trống!");
            txttencv.requestFocus();
            return;
        }

        try {
            int maCV = Integer.parseInt(maCVStr);
            double phuCap = phuCapStr.isEmpty() ? 0 : Double.parseDouble(phuCapStr);
            
            // Đóng gói đủ 4 tham số
            model.ChucVu cv = new model.ChucVu(maCV, tenCV, phuCap, ghiChu);

            if (dao.updateChucVu(cv)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thông tin chức vụ thành công!");
                loadTable();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thất bại! Vui lòng kiểm tra lại hệ thống.");
            }
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi định dạng Mã chức vụ hoặc Phụ cấp!");
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi hệ thống: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnsuacvActionPerformed

    private void btnlamlaicvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlamlaicvActionPerformed

        txtmacv.setText("");
        txttencv.setText("");
        txtphucapcv.setText(""); 
        txtghichucv.setText(""); 
        txtSearchcv.setText(""); 
        tbchucvu.clearSelection();
        loadTable();
        txttencv.requestFocus();
    }//GEN-LAST:event_btnlamlaicvActionPerformed

    private void btnSearchcvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchcvActionPerformed

        String keyword = txtSearchcv.getText().trim();
        tim(keyword);
    }//GEN-LAST:event_btnSearchcvActionPerformed
    
    // Hàm xử lý logic tìm kiếm riêng biệt 
    private void tim(String keyword) {
        // 1. Nếu từ khóa rỗng, tải lại toàn bộ danh sách gốc
        if (keyword.isEmpty()) {
            loadTable(); 
            return;
        }
        
        // 2. Xóa sạch bảng hiện tại
        tblModel.setRowCount(0);
        
        // 3. Gọi hàm tìm kiếm từ DAO 
        java.util.List<model.ChucVu> list = dao.searchChucVu(keyword);
        
        // 4. Kiểm tra và đổ dữ liệu
        if (list.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy chức vụ nào có chữ: " + keyword);
        } else {
            for (model.ChucVu cv : list) {
                tblModel.addRow(new Object[]{
                    cv.getMaCV(),
                    cv.getTenCV(),
                    cv.getPhuCap()
                });
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChucVuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChucVuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChucVuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChucVuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
                // Dùng chủ đề sáng, phẳng giống IntelliJ IDEA
                com.formdev.flatlaf.FlatIntelliJLaf.setup(); 
            } catch (Exception ex) {
                System.err.println("Lỗi khởi tạo giao diện FlatLaf");
                ex.printStackTrace();
            }

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new FMainQLNS().setVisible(true);
                }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchcv;
    private javax.swing.JButton btnlamlaicv;
    private javax.swing.JButton btnsuacv;
    private javax.swing.JButton btnthemcv;
    private javax.swing.JButton btnxoacv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbchucvu;
    private javax.swing.JTextField txtSearchcv;
    private javax.swing.JTextArea txtghichucv;
    private javax.swing.JTextField txtmacv;
    private javax.swing.JTextField txtphucapcv;
    private javax.swing.JTextField txttencv;
    // End of variables declaration//GEN-END:variables
}
