/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author DELL
 */
public class FMainQLNS extends javax.swing.JFrame {

    /**
     * Creates new form FMainQLNS
     */
    public FMainQLNS() {
        initComponents();
        
        // 1. THIET LAP KICH THUOC
        setSize(1100, 750); 
        setLocationRelativeTo(null);
        getContentPane().setLayout(null); 
        jLabel1.setBounds(0, 0, 1100, 750); // Ảnh nền
        jLabel2.setBounds(0, 0, 1100, 750); // Kính mờ
        
        // 2. TAO TIEU DE BANG
        jLabel3.setBounds(380, -120, 700, 750); 
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT); 
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.CENTER);   
        
        String myText = "<html><div style='text-align: left;'>"
                      + "<span style='font-size: 45px; color: #ffffff;'><b>QUẢN LÝ NHÂN SỰ</b></span><br>"
                      + "<span style='font-size: 14px; color: #dcdde1;'><i>Lập trình nâng cao - Ứng dụng tạo phần mềm quản lý nhân sự</i></span>"
                      + "</div></html>";
        jLabel3.setText(myText);
        
        // 3. SET LOGO UNG DUNG
        try {
            java.net.URL iconUrl = getClass().getResource("/images/logo.jpg");
            if (iconUrl != null) {
                setIconImage(new javax.swing.ImageIcon(iconUrl).getImage()); 
            }
        } catch (Exception e) {}

        // 4. XỬ LÝ ẢNH NỀN 
        try {
            // Lấy ảnh 
            javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(getClass().getResource("/nen.jpg"));
            // Kéo dãn ảnh
            java.awt.Image scaledImage = originalIcon.getImage().getScaledInstance(1100, 750, java.awt.Image.SCALE_SMOOTH);
            jLabel1.setIcon(new javax.swing.ImageIcon(scaledImage));
            jLabel2.setOpaque(true);
            jLabel2.setBackground(new java.awt.Color(0, 0, 0, 120)); 
            
        } catch (Exception e) {
            System.err.println("Lỗi load ảnh: " + e.getMessage());
        }

        // 5. ÉP BUỘC THỨ TỰ CÁC LỚP
        getContentPane().setComponentZOrder(jLabel3, 0); 
        getContentPane().setComponentZOrder(jLabel2, 1); 
        getContentPane().setComponentZOrder(jLabel1, 2); 
        
        // 6. THÊM SỰ KIỆN CLICK CHO MENU HELP
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Viết một câu thông báo dài, dùng HTML để xuống dòng và tô màu cho đẹp
                String helpMessage = "<html><body style='width: 350px; font-family: Segoe UI;'>"
                        + "<h3 style='color: #2980b9; margin-top: 0;'>Phần mềm Quản lý Nhân sự v1.0</h3>"
                        + "<p>Chào mừng bạn đến với hệ thống quản lý. Phần mềm cung cấp các công cụ hỗ trợ tối ưu:</p>"
                        + "<ul style='margin-bottom: 15px;'>"
                        + "<li>Quản lý và thiết lập danh mục Phòng ban.</li>"
                        + "<li>Theo dõi thông tin và phân quyền Chức vụ.</li>"
                        + "<li>Cập nhật hồ sơ, lương thưởng Nhân viên.</li>"
                        + "</ul>"
                        + "<hr style='border: 1px solid #bdc3c7;'>"
                        + "<p style='color: #e74c3c;'><b>Kênh hỗ trợ kỹ thuật:</b></p>"
                        + "<p>📞 Hotline: <b>09.xxxx.xxxx</b> (Zalo/Call)<br>"
                        + "📧 Email: hotro@phanmemqlns.com<br>"
                        + "⏰ Giờ làm việc: 8:00 - 17:00 (Thứ 2 - Thứ 6)</p>"
                        + "<p><i>Vui lòng chuẩn bị sẵn UltraViewer/TeamViewer khi liên hệ để được hỗ trợ nhanh nhất!</i></p>"
                        + "</body></html>";
                
                // Hiển thị bảng thông báo (Popup)
                javax.swing.JOptionPane.showMessageDialog(
                        FMainQLNS.this, 
                        helpMessage, 
                        "Trung tâm Trợ giúp", 
                        javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mn_phongban = new javax.swing.JMenuItem();
        mn_chucvu = new javax.swing.JMenuItem();
        mn_nhanvien = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm QLNS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nen.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 280));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel3.setText("QUẢN LÍ NHÂN SỰ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 270));

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));
        jMenuBar1.setOpaque(true);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMenuItem1.setText("Thoát");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Danh mục");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        mn_phongban.setText("Phòng ban");
        mn_phongban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_phongbanActionPerformed(evt);
            }
        });
        jMenu2.add(mn_phongban);

        mn_chucvu.setText("Chức vụ");
        mn_chucvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_chucvuActionPerformed(evt);
            }
        });
        jMenu2.add(mn_chucvu);

        mn_nhanvien.setText("Nhân viên");
        mn_nhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_nhanvienActionPerformed(evt);
            }
        });
        jMenu2.add(mn_nhanvien);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mn_chucvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_chucvuActionPerformed
        // Khởi tạo form Chức vụ
        view.ChucVuForm cvForm = new view.ChucVuForm();
        // Cho phép form hiển thị lên màn hình
        cvForm.setVisible(true);
    }//GEN-LAST:event_mn_chucvuActionPerformed

    private void mn_nhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_nhanvienActionPerformed
        NhanVienForm n=new NhanVienForm();
        n.setVisible(true);
    }//GEN-LAST:event_mn_nhanvienActionPerformed

    private void mn_phongbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_phongbanActionPerformed
        PhongBanForm n=new PhongBanForm();
        n.setVisible(true);
    }//GEN-LAST:event_mn_phongbanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            com.formdev.flatlaf.FlatLightLaf.setup();
        } catch (Exception ex) {
            System.err.println("Không load được thư viện FlatLaf");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMainQLNS().setVisible(true);
            }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mn_chucvu;
    private javax.swing.JMenuItem mn_nhanvien;
    private javax.swing.JMenuItem mn_phongban;
    // End of variables declaration//GEN-END:variables
}
