/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.HeadlessException;
import java.sql.SQLException;

/**
 *
 * @author DELL
 */
public class PhongBanForm extends javax.swing.JFrame {
    
    private dao.PhongBanDAO dao = new dao.PhongBanDAO(); 
    private javax.swing.table.DefaultTableModel tblModel;
    /**
     * Creates new form PhongBanForm
     */
    //  KHOI TAO FORM
    public PhongBanForm() {
        initComponents();
        getContentPane().setBackground(java.awt.Color.WHITE); 
        initTable();
        loadTable();
//        txtmapb.setEnabled(false);
        getContentPane().setBackground(java.awt.Color.WHITE);
        
        javax.swing.JPanel decorator = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                g2.setColor(new java.awt.Color(220, 220, 220));
                g2.drawLine(450, 15, 450, getHeight() - 30);
            }
            @Override
            public boolean contains(int x, int y) { return false; }
        };
        decorator.setOpaque(false);
        setGlassPane(decorator);
        decorator.setVisible(true);
    }
    
    // 1. Hàm định dạng bảng
    private void initTable() {
        tblModel = (javax.swing.table.DefaultTableModel) tbphongban.getModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã PB", "Tên Phòng Ban", "Số Điện Thoại", "Ghi Chú"});
        
        // 1. DỌN DẸP BẢNG
        tbphongban.setShowVerticalLines(true); 
        tbphongban.setShowHorizontalLines(true);
        tbphongban.setGridColor(new java.awt.Color(190, 190, 190));
        
        // 2. TRANG TRÍ HEADER 
        javax.swing.table.JTableHeader header = tbphongban.getTableHeader();
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13)); 
        header.setBackground(java.awt.Color.WHITE); 
        header.setForeground(new java.awt.Color(70, 70, 70));
        header.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(200, 200, 200)));

        // 3. ĐÓNG KHUNG "DANH SÁCH PHÒNG BAN"
        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)),
            "Danh sách phòng ban",
            javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
            javax.swing.border.TitledBorder.DEFAULT_POSITION,
            new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13),
            new java.awt.Color(41, 128, 185) 
        ));
        
        // 4. CĂN CHỈNH ĐỘ RỘNG TỪNG CỘT 
        javax.swing.table.TableColumnModel columnModel = tbphongban.getColumnModel();
        
        columnModel.getColumn(0).setPreferredWidth(50);  // Mã PB (
        columnModel.getColumn(1).setPreferredWidth(130); // Tên PB 
        columnModel.getColumn(2).setPreferredWidth(100); // SĐT
        columnModel.getColumn(3).setPreferredWidth(200); // Ghi chú
    }

    // 2. Hàm tải dữ liệu từ CSDL lên bảng
    private void loadTable() {
        // Xóa sạch dữ liệu cũ
        tblModel.setRowCount(0); 
        
        // Gọi hàm getAll() từ DAO
        java.util.List<model.PhongBan> list = dao.getAll();
        
        // Đổ dữ liệu mới vào bảng
        for (model.PhongBan pb : list) {
            tblModel.addRow(new Object[]{
                pb.getMaPB(),
                pb.getTenPB(),
                pb.getDienThoai(),
                pb.getGhiChu()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmapb = new javax.swing.JTextField();
        txttenpb = new javax.swing.JTextField();
        txtsdtpb = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaghichupb = new javax.swing.JTextArea();
        btnthempb = new javax.swing.JButton();
        btnxoapb = new javax.swing.JButton();
        btnsuapb = new javax.swing.JButton();
        btnlamlaipb = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbphongban = new javax.swing.JTable();
        txtSearchpb = new javax.swing.JTextField();
        btnSearchpb = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cập nhật phòng ban");
        setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(974, 563));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Thông tin phòng ban");

        jLabel2.setText("Mã phòng ban:");

        jLabel3.setText("Tên phòng ban:");

        jLabel4.setText("Số điện thoại:");

        jLabel5.setText("Ghi chú:");

        txaghichupb.setColumns(20);
        txaghichupb.setRows(5);
        jScrollPane1.setViewportView(txaghichupb);

        btnthempb.setText("Thêm");
        btnthempb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthempbActionPerformed(evt);
            }
        });

        btnxoapb.setText("Xóa");
        btnxoapb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoapbActionPerformed(evt);
            }
        });

        btnsuapb.setText("Sửa");
        btnsuapb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuapbActionPerformed(evt);
            }
        });

        btnlamlaipb.setText("Làm lại");
        btnlamlaipb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlamlaipbActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Danh sách phòng ban hiện có");

        tbphongban.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã PB", "Tên PB", "Sđt", "Ghi chú"
            }
        ));
        tbphongban.setName(""); // NOI18N
        tbphongban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbphongbanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbphongban);

        btnSearchpb.setText("Tìm");
        btnSearchpb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchpbActionPerformed(evt);
            }
        });

        jLabel7.setText("Tìm kiếm:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnthempb)
                        .addGap(18, 18, 18)
                        .addComponent(btnxoapb)
                        .addGap(18, 18, 18)
                        .addComponent(btnsuapb)
                        .addGap(18, 18, 18)
                        .addComponent(btnlamlaipb))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(txtmapb)
                            .addComponent(txttenpb)
                            .addComponent(txtsdtpb)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchpb, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnSearchpb, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtmapb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSearchpb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchpb))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txttenpb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtsdtpb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnthempb)
                            .addComponent(btnxoapb)
                            .addComponent(btnsuapb)
                            .addComponent(btnlamlaipb)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnthempbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthempbActionPerformed
        // 1. Lấy dữ liệu từ các ô Textbox
        String tenPB = txttenpb.getText().trim();
        String dienThoai = txtsdtpb.getText().trim();
        String ghiChu = txaghichupb.getText().trim();

        // 2. Bắt lỗi không được để trống Tên phòng ban
        if (tenPB.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập tên phòng ban!");
            txttenpb.requestFocus();
            return;
        }

        // 3. Kết nối CSDL và gọi Stored Procedure
        try {
            java.sql.Connection conn = util.DBConnection.getConnection();
            
            String sql = "{CALL sp_ThemPhongBan(?, ?, ?)}";
            java.sql.CallableStatement cs = conn.prepareCall(sql);
            
            cs.setString(1, tenPB);
            cs.setString(2, dienThoai);
            cs.setString(3, ghiChu);
            
            // Thực thi thủ tục
            cs.execute();
            
            // Thông báo thành công
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm phòng ban thành công!");
            
            loadTable(); // Tải lại bảng để thấy dữ liệu mới xuất hiện ngay lập tức
            btnlamlaipbActionPerformed(evt); // Gọi luôn nút Làm Lại để xóa trắng các ô chữ cho gọn
            
            // Đóng kết nối
            cs.close();
            conn.close();
            
        } catch (java.awt.HeadlessException | java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi Thêm: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnthempbActionPerformed

    private void tbphongbanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbphongbanMouseClicked
        int row = tbphongban.getSelectedRow();
        if (row >= 0) {
            // Lấy dữ liệu từ các cột của dòng đó và đẩy lên các TextBox
            txtmapb.setText(tbphongban.getValueAt(row, 0).toString());
            txttenpb.setText(tbphongban.getValueAt(row, 1).toString());
            
            Object sdt = tbphongban.getValueAt(row, 2);
            txtsdtpb.setText(sdt != null ? sdt.toString() : "");
            
            Object ghiChu = tbphongban.getValueAt(row, 3);
            txaghichupb.setText(ghiChu != null ? ghiChu.toString() : "");
        }
    }//GEN-LAST:event_tbphongbanMouseClicked

    private void btnxoapbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoapbActionPerformed
        // 1. Lấy chuỗi từ ô nhập Mã PB
        String maPBStr = txtmapb.getText().trim();

        // 2. Kiểm tra rỗng 
        if (maPBStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn hoặc nhập mã phòng ban cần xóa!");
            return;
        }

        int maPB;
        
        // 3. Kiểm tra định dạng số 
        try {
            maPB = Integer.parseInt(maPBStr);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Mã phòng ban phải là số!");
            return;
        }

        // 4. Hiển thị hộp thoại xác nhận
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                "Bạn có chắc muốn xóa phòng ban này?", 
                "Xác nhận", 
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        // 5. Nếu chọn YES (Đồng ý xóa)
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                // Gọi hàm deletePhongBan từ DAO 
                if (dao.deletePhongBan(maPB)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Xóa phòng ban thành công!");
                    loadTable(); 
                    
                    // Làm sạch các ô text
                    txtmapb.setText("");
                    txttenpb.setText("");
                    txtsdtpb.setText("");
                    txaghichupb.setText("");
                } else {
                    // Nếu DAO trả về false 
                    javax.swing.JOptionPane.showMessageDialog(this, "Xóa thất bại! Vui lòng kiểm tra lại dữ liệu.");
                }
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi hệ thống: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnxoapbActionPerformed

    private void btnsuapbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuapbActionPerformed
        // 1. Kiểm tra xem người dùng đã chọn phòng ban trên bảng chưa
        String maPBStr = txtmapb.getText().trim();
        if (maPBStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng click chọn một phòng ban trên bảng để sửa!");
            return;
        }

        // 2. Lấy dữ liệu mới từ các ô nhập liệu
        String tenPB = txttenpb.getText().trim();
        String dienThoai = txtsdtpb.getText().trim();
        String ghiChu = txaghichupb.getText().trim();

        // 3. Bắt lỗi không được để trống Tên phòng ban
        if (tenPB.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tên phòng ban không được để trống!");
            txttenpb.requestFocus();
            return;
        }

        // 4. Ép kiểu Mã PB sang số nguyên và đóng gói vào Object
        try {
            int maPB = Integer.parseInt(maPBStr);
            model.PhongBan pb = new model.PhongBan(maPB, tenPB, dienThoai, ghiChu);

            // 5. Gọi hàm DAO để thực thi Sửa vào Database
            if (dao.updatePhongBan(pb)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thông tin phòng ban thành công!");
                
                // Cập nhật lại JTable để thấy dữ liệu mới
                loadTable();
                
                // btnlamlaipbActionPerformed(evt); 
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thất bại! Vui lòng kiểm tra lại hệ thống.");
            }
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi định dạng Mã phòng ban!");
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi hệ thống: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnsuapbActionPerformed

    private void btnlamlaipbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlamlaipbActionPerformed
        // 1. Xóa trắng toàn bộ các ô nhập liệu
        txtmapb.setText("");
        txttenpb.setText("");
        txtsdtpb.setText("");
        txaghichupb.setText("");
        
        // Xóa ô tìm kiếm (nếu người dùng đang gõ dở)
        txtSearchpb.setText(""); 
        
        // 2. Bỏ highlight (chọn) trên bảng
        tbphongban.clearSelection();
        
        // 3. Tải lại toàn bộ dữ liệu gốc lên bảng 
        loadTable();
        txttenpb.requestFocus();
    }//GEN-LAST:event_btnlamlaipbActionPerformed

    private void btnSearchpbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchpbActionPerformed

        String keyword = txtSearchpb.getText().trim();
        tim(keyword);
    }//GEN-LAST:event_btnSearchpbActionPerformed
    
    // Hàm xử lý logic tìm kiếm riêng biệt giống trong ảnh
    private void tim(String keyword) {
        // 1. Nếu từ khóa rỗng, tải lại toàn bộ danh sách gốc
        if (keyword.isEmpty()) {
            loadTable(); 
            return;
        }
        
        // 2. Xóa sạch bảng hiện tại
        tblModel.setRowCount(0);
        
        // 3. Gọi hàm tìm kiếm từ DAO (Hàm DAO ở Bước 2 bài trước mình gửi)
        java.util.List<model.PhongBan> list = dao.searchPhongBan(keyword);
        
        // 4. Kiểm tra và đổ dữ liệu
        if (list.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy phòng ban nào có chữ: " + keyword);
        } else {
            for (model.PhongBan pb : list) {
                tblModel.addRow(new Object[]{
                    pb.getMaPB(),
                    pb.getTenPB(),
                    pb.getDienThoai(),
                    pb.getGhiChu()
                });
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhongBanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhongBanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhongBanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhongBanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
                com.formdev.flatlaf.FlatIntelliJLaf.setup(); 
            } catch (Exception ex) {
                System.err.println("Lỗi khởi tạo giao diện FlatLaf");
                ex.printStackTrace();
            }

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new FMainQLNS().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchpb;
    private javax.swing.JButton btnlamlaipb;
    private javax.swing.JButton btnsuapb;
    private javax.swing.JButton btnthempb;
    private javax.swing.JButton btnxoapb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbphongban;
    private javax.swing.JTextArea txaghichupb;
    private javax.swing.JTextField txtSearchpb;
    private javax.swing.JTextField txtmapb;
    private javax.swing.JTextField txtsdtpb;
    private javax.swing.JTextField txttenpb;
    // End of variables declaration//GEN-END:variables
}
